apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: roundrobin-cert
  namespace: flight-search
spec:
  secretName: roundrobin-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: roundrobin.cutemiya.ru
  dnsNames:
  - roundrobin.cutemiya.ru

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sticky-cert
  namespace: flight-search
spec:
  secretName: sticky-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sticky.cutemiya.ru
  dnsNames:
  - sticky.cutemiya.ru

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: random-cert
  namespace: flight-search
spec:
  secretName: random-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: random.cutemiya.ru
  dnsNames:
  - random.cutemiya.ru