apiVersion: v1
kind: Service
metadata:
  name: flight-app-service-h
  namespace: flight-search
spec:
  selector:
    app: flight-app
  ports:
  - port: 80
    targetPort: 4000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hwr-host
  namespace: flight-search
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`hwr.cutemiya.ru`)
    kind: Rule
    services:
    - name: flight-app-service-h
      port: 80
      strategy: hrw
  tls:
    certResolver: letsencrypt