apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flight-app-sticky
  namespace: flight-search
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "sticky-session"
    traefik.ingress.kubernetes.io/session-cookie-secure: "true"
spec:
  tls:
  - hosts:
    - sticky.cutemiya.ru
    secretName: flight-app-tls
  rules:
  - host: sticky.cutemiya.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flight-app-service
            port:
              number: 80