apiVersion: v1
kind: ConfigMap
metadata:
  name: flight-app-config
  namespace: flight-search
data:
  NODE_ENV: "production"
  PORT: "4000"
  GRAPHIQL_ENABLED: "true"
  CORS_ORIGIN: "*"
  # Количество реплик приложения (для балансировки)
  APP_REPLICAS: "2"
  # Настройки подключения к БД (реальные будут в secret)
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "flightdb"