apiVersion: v1
kind: Service
metadata:
  name: flight-app-service
  namespace: flight-search
  labels:
    app: flight-app
    component: backend
  annotations:
    # Traefik специфичные аннотации
    traefik.ingress.kubernetes.io/service-loadbalancer: "true"
spec:
  selector:
    app: flight-app
    component: backend
  ports:
  - name: http
    port: 80
    targetPort: 4000
    protocol: TCP
  type: ClusterIP
  # SessionAffinity: None (по умолчанию) - это Round Robin