apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flight-app
  namespace: flight-search
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - main.cutemiya.ru
    secretName: main-cutemiya-ru-tls
  rules:
  - host: main.cutemiya.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flight-app
            port:
              number: 4000