apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compress
  namespace: flight-search
spec:
  compress: {}

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: flight-search-compress
  namespace: flight-search
spec:
  compress:
    excludedContentTypes:
      - text/event-stream