apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-app-weight-1
  namespace: flight-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-app
      component: backend
      weight: "1"
  template:
    metadata:
      labels:
        app: flight-app
        component: backend
        weight: "1"
    spec:
      containers:
      - name: flight-app
        image: registry.cutemiya.ru/flight-search-app:latest
        ports:
        - containerPort: 4000
        env:
        - name: WEIGHT
          value: "1"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-app-weight-1-b
  namespace: flight-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-app
      component: backend
      weight: "1-b"
  template:
    metadata:
      labels:
        app: flight-app
        component: backend
        weight: "1-b"
    spec:
      containers:
      - name: flight-app
        image: registry.cutemiya.ru/flight-search-app:latest
        ports:
        - containerPort: 4000
        env:
        - name: WEIGHT
          value: "1-b"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-app-weight-8
  namespace: flight-search
spec:
  replicas: 8
  selector:
    matchLabels:
      app: flight-app
      component: backend
      weight: "8"
  template:
    metadata:
      labels:
        app: flight-app
        component: backend
        weight: "8"
    spec:
      containers:
      - name: flight-app
        image: registry.cutemiya.ru/flight-search-app:latest
        ports:
        - containerPort: 4000
        env:
        - name: WEIGHT
          value: "8"